# Generated by Django 4.2 on 2023-05-05 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="pub_date",
            new_name="creation_date",
        ),
    ]
