# Generated by Django 4.2 on 2023-05-05 21:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_tagging_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tagging",
            name="creation_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
